version = "1.1.16"

[class]
chromium = ""
"org.kde.ark" = ""
code-oss = ""
"com.obsproject.Studio" = ""
Thunderbird = "󰇮"
Chromium-browser = ""
Code = ""
Nightly = "󰈹"
"com.github.wwmm.easyeffects" = "󰝚"
"org.kde.kcharselect" = ""
polkit-gnome-authentication-agent-1 = ""
"/pdf/" = "󰈦"
Alacritty = "󰞷"
librewolf = "󰈹"
obs = ""
gnome-power-statistics = "󰂑"
Anydesk = "󰢹"
Gimp = ""
steam = ""
steam_app_1266700 = "󰢚"
anki = ""
FreeTube = ""
mpv = ""
yuzu = "󰟡"
discord = ""
equibop = ""
Chromium = ""
zim = "󰏪"
steam_app_2281730 = "󰜃"
dolphin-emu = "󱢴"
whatsapp-for-linux = ""
Pinta = "󰃣"
"org.inkscape.Inkscape" = ""
spotify = ""
"org.remmina.Remmina" = ""
pcmanfm = "󰉋"
polkit-gnome-authentication-agent0 = ""
"org.telegram.desktop" = ""
foot = "󰞷"
betterbird = "󰇮"
pinta = "󰃣"
audacity = ""
chatall = ""
steam_app_1623730 = "󰐝"
alacrittyclipboard = ""
Insomnia = ""
citra = ""
firefoxdeveloperedition = "󰈹"
"blueberry.py" = "󰂯"
vlc = "󰕼"
"at.yrlf.wl_mirror" = "󰍹"
steam_app_246620 = ""
wdisplays = "󰍹"
qtalarm = "󰀠"
SchildiChat = ""
Wfica = ""
telegramdesktop = ""
copyq = ""
deluge = ""
r2modman = "󰖷"
"org.qutebrowser.qutebrowser" = "󰖟"
"org.qbittorrent.qBittorrent" = "󱑤"
Zim = "󰏪"
clonehero = "󰋄"
GParted = "󰋊"
Slack = "󰒱"
gcr-prompter = ""
steam_app_783770 = "󰜃"
YARG = "󰋄"
pcmanfm-gtk4 = "󰉋"
"FTL.amd64" = ""
steamwebhelper = ""
"Microsoft Teams - Insiders" = "󰊻"
"org.twosheds.iwgtk" = "󰖩"
vesktop = ""
Dorion = ""
thunderbird = "󰇮"
"net.nokyan.Resources" = "󰉹"
"org.gnome.Software" = "󰓜"
Element = ""
"org.kde.neochat" = ""
steam_app_1817070 = "󱇪"
"org.kde.discover" = "󰓜"
gucharmap = ""
"Microsoft Teams - Preview" = "󰊻"
stoken-gui = "󰌆"
Steam = ""
steam_app_803330 = "󰢚"
Telegram = ""
nheko = ""
image-roll = ""
"org.kde.gwenview" = ""
mpvsounds = "󰈸"
firefox = "󰈹"
yakyak = "󰋉"
rpcs4 = ""
Cemu = "󰜭"
"io.gpt4all.gpt4all-chat" = ""
pcmanfm-qt = "󰉋"
steam_app_1872550 = "󰢚"
Spotify = ""
steam_app_714010 = "󰜃"
"com.github.weclaw2.ImageRoll" = ""
galculator = "󰪚"
"io.github.Qalculate.qalculate-qt" = "󰪚"
"app.drey.Warp" = "󰒖"
pavucontrol = "󰕾"
"waydroid.com.citrix.Receiver" = ""
"chrome-eafkcfmjahamkcccoaiancpfpphaflnj-Default" = ""
"chrome-hkleablohhooipcdnigfpmlgpkjakgkk-Default" = ""
"chrome-jdcnidlfpalkfchkfdfdfikmihioopic-Default" = ""
Bitwarden = ""
teams-for-linux = "󰊻"
"CombatMaster.x86_64" = "󰜃"
floorp = "󰈹"
Postman = "󰇮"
Google-chrome = ""
XEyes = "󱗣"
ryujinx = "󰟡"
DEFAULT = "󰖯"
"org.gnome.Loupe" = "󰋩"
"sc2_x64.exe" = ""
"lmirtechconsole.exe" = "󰍹"
steam_app_1817190 = "󱇪"
"org.kde.dolphin" = "󰉋"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
0 = "0"
1 = "1"
2 = "2"
3 = "3"
4 = "4"
5 = "5"
6 = "6"
7 = "7"
8 = "8"
9 = "9"
10 = "10"

[title_in_class.floorp]
".* - Google Drive — Ablaze Floorp" = ""
".* - Lemmy — Ablaze Floorp" = ""
".* - Google Search — Ablaze Floorp" = ""
".* - Beehaw — Ablaze Floorp" = ""
"Voice - (.*) Messages — Ablaze Floorp" = "󰏲"
"Google Calendar — Ablaze Floorp" = "󰸗"
".* - YouTube — Ablaze Floorp" = "󰗃"
"X — Ablaze Floorp" = ""
".* - Apps on Google Play — Ablaze Floorp" = ""
"Voice - (.*) Spam — Ablaze Floorp" = "󰏲"
"Google Calendar - .* — Ablaze Floorp" = "󰸗"
".*Android Apps on Google Play — Ablaze Floorp" = ""
"Voice - (.*) Archive — Ablaze Floorp" = "󱉙"
"Voice - Calls — Ablaze Floorp" = "󰏲"
".* - Lemmy.ca — Ablaze Floorp" = ""
".*Ablaze Floorp Private Browsing" = "󰈉"
"GitHub — Ablaze Floorp" = ""
"Lemmy - .*Ablaze Floorp" = ""
"Frozen Lemmy - .*Ablaze Floorp" = ""
".* - Frozen Lemmy — Ablaze Floorp" = ""
"Beehaw - .*Ablaze Floorp" = ""
"Voice - (.*) Voicemail — Ablaze Floorp" = ""
".* / X — Ablaze Floorp" = ""
".* - Invidious — Ablaze Floorp" = "󰗃"
"Lemmy.ca - .*Ablaze Floorp" = ""
".*nitter — Ablaze Floorp" = ""

[title_in_class.Alacritty]
"(.*) - NVIM" = "󱩼"

[title_in_class.pcmanfm]
".config" = "󱁿"
"Copy Files" = "󱁥"
Documents = "󰲂"
Public = "󰉌"
Pictures = "󰉏"
Videos = "󱧺"
Torrents = "󰉍"
Music = "󱍙"
Preferences = ""
Notebooks = "󰣞"
Templates = "󱧺"
Downloads = "󰉍"

[title_in_class.pcmanfm-qt]
Public = "󰉌"
Pictures = "󰉏"
Notebooks = "󰣞"
"Copy Files" = "󱁥"
Videos = "󱧺"
Music = "󱍙"
Torrents = "󰉍"
Templates = "󱧺"
Preferences = ""
Documents = "󰲂"
".config" = "󱁿"
Downloads = "󰉍"

[title_in_class.librewolf]
".* - Lemmy.ca — LibreWolf" = ""
"Frozen Lemmy - .*LibreWolf" = ""
".* - Google Search — LibreWolf" = ""
".* - Lemmy — LibreWolf" = ""
".* - Frozen Lemmy — LibreWolf" = ""
"Lemmy - .*LibreWolf" = ""
"Voice - (.*) Voicemail — LibreWolf" = ""
".* - YouTube — LibreWolf" = "󰗃"
"Voice - (.*) Archive — LibreWolf" = "󱉙"
"Voice - Calls — LibreWolf" = "󰏲"
".*LibreWolf Private Browsing" = "󰈉"
"Lemmy.ca - .*LibreWolf" = ""
"Google Calendar — LibreWolf" = "󰸗"
"Voice - (.*) Messages — LibreWolf" = "󰏲"
"GitHub — LibreWolf" = ""
".* / X — LibreWolf" = ""
"Google Calendar - .* — LibreWolf" = "󰸗"
".* - Beehaw — LibreWolf" = ""
"Beehaw - .*LibreWolf" = ""
".*Android Apps on Google Play — LibreWolf" = ""
".* - Invidious — LibreWolf" = "󰗃"
"Voice - (.*) Spam — LibreWolf" = "󰏲"
".*nitter — LibreWolf" = ""
".* - Google Drive — LibreWolf" = ""
".* - Apps on Google Play — LibreWolf" = ""
"X — LibreWolf" = ""

[title_in_class."org.kde.dolphin"]
"Downloads — Dolphin" = "󰉍"
".config — Dolphin" = "󱁿"
"Copying — Dolphin" = "󱁥"
"Configure — Dolphin" = ""
"Templates — Dolphin" = "󱧺"
"Videos — Dolphin" = "󱧺"
"Torrents — Dolphin" = "󰉍"
"Music — Dolphin" = "󱍙"
"Home — Dolphin" = "󱂵"
"Notebooks — Dolphin" = "󰣞"
"Documents — Dolphin" = "󰲂"
"Pictures — Dolphin" = "󰉏"
"Public — Dolphin" = "󰉌"

[title_in_class.chromium]
".* - Frozen Lemmy  - Chromium" = ""
"Voice - (.*) Archive  - Chromium" = "󱉙"
".* - Beehaw  - Chromium" = ""
".* - YouTube  - Chromium" = "󰗃"
"X  - Chromium" = ""
"Frozen Lemmy - .*Chromium" = ""
"Google Calendar - .*  - Chromium" = "󰸗"
".* - Lemmy.ca  - Chromium" = ""
"Beehaw - .*Chromium" = ""
".* - Google Search  - Chromium" = ""
".*nitter  - Chromium" = ""
".* - Google Drive  - Chromium" = ""
"INC. - Dashboard > Home - Chromium" = "󰥔"
"Voice - Calls  - Chromium" = "󰏲"
"Dashboards - Chromium" = ""
"MAX.*Chromium" = ""
"GitHub  - Chromium" = ""
"Voice - (.*) Voicemail  - Chromium" = ""
"Lemmy - .*Chromium" = ""
"Voice - (.*) Spam  - Chromium" = "󰏲"
"Lemmy.ca - .*Chromium" = ""
".* - Lemmy  - Chromium" = ""
"Voice - (.*) Messages  - Chromium" = "󰏲"
".*Android Apps on Google Play  - Chromium" = ""
"Google Calendar  - Chromium" = "󰸗"
".* / X  - Chromium" = ""
".* - Apps on Google Play  - Chromium" = ""

[title_in_class.firefox]
".* - Invidious — Mozilla Firefox" = "󰗃"
".*nitter — Mozilla Firefox" = ""
"Frozen Lemmy - .*Firefox" = ""
"Lemmy - .*Firefox" = ""
".* - Beehaw — Mozilla Firefox" = ""
"GitHub — Mozilla Firefox" = ""
"Google Calendar — Mozilla Firefox" = "󰸗"
"Voice - (.*) Spam — Mozilla Firefox" = "󰏲"
"X — Mozilla Firefox" = ""
".* - Google Search — Mozilla Firefox" = ""
".*Mozilla Firefox Private Browsing" = "󰈉"
"Lemmy.ca - .*Firefox" = ""
"Voice - (.*) Messages — Mozilla Firefox" = "󰏲"
".* - Lemmy.ca — Mozilla Firefox" = ""
".* / X — Mozilla Firefox" = ""
"Google Calendar - .* — Mozilla Firefox" = "󰸗"
".* - YouTube — Mozilla Firefox" = "󰗃"
".* - Lemmy — Mozilla Firefox" = ""
"Voice - (.*) Archive — Mozilla Firefox" = "󱉙"
".* - Apps on Google Play — Mozilla Firefox" = ""
"Beehaw - .*Firefox" = ""
".*Android Apps on Google Play — Mozilla Firefox" = ""
"Voice - (.*) Voicemail — Mozilla Firefox" = ""
".* - Google Drive — Mozilla Firefox" = ""
".* - Frozen Lemmy — Mozilla Firefox" = ""
"Voice - Calls — Mozilla Firefox" = "󰏲"

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)TestApp" = ""
"[Ss]team" = "^(Friends List.*)?$"
"" = "^$"
"(?i)fcitx" = ".*"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "<b>{name}:</b>{delim}{clients}"
workspace_empty = "<b>{name}</b>"
client = "<span alpha='70%'>{icon}</span>"
client_fullscreen = "｢{icon}｣"
client_active = "<span alpha='100%'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
