version = "1.1.14"

[class]
Spotify = ""
rpcs4 = "︁"
steam_app_2281730 = "󰜃"
Steam = ""
Code = ""
"waydroid.com.citrix.Receiver" = ""
gucharmap = ""
wdisplays = ""
"FTL.amd64" = ""
"io.gpt4all.gpt4all-chat" = ""
Nightly = ""
Google-chrome = ""
steam_app_783770 = "󰜃"
spotify = ""
image-roll = ""
zim = "󰏪"
discord = ""
"org.kde.ark" = ""
clonehero = "󰋄"
Anydesk = ""
Gimp = ""
galculator = "󰃬"
alacrittyclipboard = ""
Zim = "󰏪"
thunderbird = "󰇮"
Bitwarden = ""
pavucontrol = ""
Wfica = ""
"org.twosheds.iwgtk" = ""
"com.github.weclaw2.ImageRoll" = ""
Postman = "󰇮"
firefoxdeveloperedition = ""
"at.yrlf.wl_mirror" = ""
"com.obsproject.Studio" = "󰻂"
"com.github.wwmm.easyeffects" = ""
Cemu = "︁"
"/GParted/" = "󰋊"
nheko = ""
Slack = "󰒱"
audacity = ""
"blueberry.py" = "󰂯"
chromium = ""
steam_app_1266700 = "󰢚"
telegramdesktop = ""
steam_app_714010 = "󰜃"
yuzu = "︁"
XEyes = "󰈈"
SchildiChat = ""
"Microsoft Teams - Insiders" = "󰊻"
steamwebhelper = ""
Element = ""
steam_app_246620 = ""
"org.kde.dolphin" = "󰉋"
pcmanfm-qt = "󰉋"
Chromium = ""
Chromium-browser = ""
"org.inkscape.Inkscape" = ""
"Ardour-5.9.0" = ""
stoken-gui = "󰌆"
Thunderbird = "󰇮"
foot = ""
"org.kde.kcharselect" = ""
citra = "︁"
steam_app_803330 = "󰢚"
dolphin-emu = "︁"
GParted = "󰋊"
"org.qutebrowser.qutebrowser" = ""
"/pdf/" = ""
"CombatMaster.x86_64" = "󰜃"
Alacritty = ""
steam_app_1872550 = "󰢚"
DEFAULT = ""
pinta = "󰃣"
deluge = "󱑤"
copyq = "󰅇"
"org.telegram.desktop" = ""
gcr-prompter = ""
"net.nokyan.Resources" = ""
Telegram = ""
obs = "󰻂"
YARG = "󰋄"
"lmirtechconsole.exe" = ""
qtalarm = "󰀠"
steam = ""
firefox = ""
FreeTube = ""
Pinta = "󰃣"
polkit-gnome-authentication-agent0 = ""
Insomnia = ""
"org.qbittorrent.qBittorrent" = "󱑤"
code-oss = ""
steam_app_1817070 = "󱇪"
"org.remmina.Remmina" = ""
pcmanfm-gtk4 = "󰉋"
mpv = ""
anki = ""
mpvrainsounds = ""
whatsapp-for-linux = ""
vlc = "󰕼"
"org.kde.ksysguard" = ""
"Microsoft Teams - Preview" = "󰊻"
gnome-power-statistics = ""
chatall = ""
"/exe/" = "󰡶"
steam_app_1623730 = "󰐝"
yakyak = "󰋉"
steam_app_1817190 = "󱇪"
teams-for-linux = "󰊻"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
10 = "ten"
2 = "2"
4 = "four"
1 = "1"
0 = "0"
3 = "three"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
scratchpad = "11"
work = "12"

[title_in_class.Alacritty]
"(.*) - NVIM" = "󱩼"

[title_in_class.chromium]
"(?i)Github" = ""
"(?i)Dashboards -.*Chromium" = ""
"/Google/" = ""
"(?i)MAX.*Chromium" = ""
"(.*)INC. - Dashboard > Home - Chromium" = ""
"(.*) - YouTube.*Chromium" = ""

[title_in_class.firefox]
"(?i)Google Calendar.*Firefox" = ""
"(?i)Github" = ""
" - YouTube — Mozilla Firefox" = ""
"/Google/" = ""
".*Twitter — Mozilla Firefox" = ""
"(?i)Google Drive.*Firefox" = ""
"(?i)Google Play.*Firefox" = ""
"Firefox .*Private Browsing" = "󰈉"
"(?i)reddit.*Firefox" = ""
"(?i)drive.*Firefox" = ""
".*nitter — Mozilla Firefox" = ""

[title_in_class.pcmanfm-qt]
Preferences = ""

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)TestApp" = ""
"[Ss]team" = "^(Friends List.*)?$"
"(?i)fcitx" = ".*"
aProgram = "^$"
"" = "^$"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "<span color='#ff4040'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
