version = "1.1.15"

[class]
Slack = "󰒱"
anki = ""
rpcs4 = ""
steam_app_1266700 = "󰢚"
Telegram = ""
Wfica = ""
"at.yrlf.wl_mirror" = "󰍹"
"Microsoft Teams - Insiders" = "󰊻"
"org.remmina.Remmina" = ""
"org.gnome.Software" = "󰓜"
pcmanfm-gtk4 = "󰉋"
steam_app_1817070 = "󱇪"
steam_app_714010 = "󰜃"
Code = ""
Google-chrome = ""
SchildiChat = ""
Nightly = "󰈹"
foot = "󰞷"
telegramdesktop = ""
"waydroid.com.citrix.Receiver" = ""
steamwebhelper = ""
Anydesk = "󰢹"
firefox = "󰈹"
gnome-power-statistics = "󰂑"
Alacritty = "󰞷"
chromium = ""
yuzu = "󰟡"
Cemu = "󰜭"
code-oss = ""
zim = "󰏪"
DEFAULT = "󰖯"
"org.kde.ark" = ""
XEyes = "󱗣"
nheko = ""
steam_app_1623730 = "󰐝"
deluge = ""
Pinta = "󰃣"
"org.qbittorrent.qBittorrent" = "󱑤"
"com.github.weclaw2.ImageRoll" = ""
thunderbird = "󰇮"
steam = ""
pcmanfm = "󰉋"
"org.gnome.Loupe" = "󰋩"
pinta = "󰃣"
polkit-gnome-authentication-agent0 = ""
steam_app_783770 = "󰜃"
spotify = ""
ryujinx = "󰟡"
"blueberry.py" = "󰂯"
galculator = "󰪚"
clonehero = "󰋄"
yakyak = "󰋉"
stoken-gui = "󰌆"
"net.nokyan.Resources" = "󰉹"
audacity = ""
gucharmap = ""
image-roll = ""
"com.obsproject.Studio" = ""
vlc = "󰕼"
mpvsounds = "󰈸"
obs = ""
qtalarm = "󰀠"
"com.github.wwmm.easyeffects" = "󰝚"
Bitwarden = ""
Chromium-browser = ""
Insomnia = ""
copyq = ""
FreeTube = ""
Steam = ""
pavucontrol = "󰕾"
teams-for-linux = "󰊻"
"org.kde.kcharselect" = ""
Gimp = ""
Spotify = ""
"lmirtechconsole.exe" = "󰍹"
"/pdf/" = "󰈦"
"FTL.amd64" = ""
"/exe/" = ""
"Microsoft Teams - Preview" = "󰊻"
chatall = ""
discord = ""
gcr-prompter = ""
"CombatMaster.x86_64" = "󰜃"
YARG = "󰋄"
Thunderbird = "󰇮"
alacrittyclipboard = ""
citra = ""
"io.gpt4all.gpt4all-chat" = ""
Element = ""
"org.inkscape.Inkscape" = ""
dolphin-emu = "󱢴"
Chromium = ""
"org.telegram.desktop" = ""
"org.twosheds.iwgtk" = "󰖩"
pcmanfm-qt = "󰉋"
polkit-gnome-authentication-agent-1 = ""
r2modman = "󰖷"
GParted = "󰋊"
steam_app_1817190 = "󱇪"
"org.qutebrowser.qutebrowser" = "󰖟"
steam_app_1872550 = "󰢚"
Postman = "󰇮"
steam_app_2281730 = "󰜃"
steam_app_246620 = ""
steam_app_803330 = "󰢚"
wdisplays = "󰍹"
"org.kde.dolphin" = "󰉋"
whatsapp-for-linux = ""
firefoxdeveloperedition = "󰈹"
mpv = ""
Zim = "󰏪"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
9 = "9"
1 = "1"
6 = "6"
2 = "2"
3 = "3"
7 = "7"
0 = "0"
5 = "5"
8 = "8"
10 = "10"
4 = "4"

[title_in_class.chromium]
".* - Frozen Lemmy  - Chromium" = ""
"Lemmy - .*Chromium" = ""
".* - Google Drive  - Chromium" = ""
".*Android Apps on Google Play  - Chromium" = ""
".*nitter  - Chromium" = ""
".* - Apps on Google Play  - Chromium" = ""
".* - Google Search  - Chromium" = ""
"Beehaw - .*Chromium" = ""
"Google Calendar - .*  - Chromium" = "󰸗"
"INC. - Dashboard > Home - Chromium" = "󰥔"
"GitHub  - Chromium" = ""
".* - Lemmy.ca  - Chromium" = ""
".* / X  - Chromium" = ""
"Google Calendar  - Chromium" = "󰸗"
".* - Beehaw  - Chromium" = ""
"Frozen Lemmy - .*Chromium" = ""
"Voice - (.*) Archive  - Chromium" = "󱉙"
"Voice - (.*) Messages  - Chromium" = "󰏲"
".* - YouTube  - Chromium" = "󰗃"
"Voice - (.*) Spam  - Chromium" = "󰏲"
"Lemmy.ca - .*Chromium" = ""
"Voice - Calls  - Chromium" = "󰏲"
"Dashboards - Chromium" = ""
"X  - Chromium" = ""
"MAX.*Chromium" = ""
"Voice - (.*) Voicemail  - Chromium" = ""
".* - Lemmy  - Chromium" = ""

[title_in_class.pcmanfm-qt]
Music = "󱍙"
Templates = "󱧺"
Notebooks = "󰣞"
Videos = "󱧺"
Pictures = "󰉏"
Documents = "󰲂"
Downloads = "󰉍"
".config" = "󱁿"
Public = "󰉌"
Torrents = "󰉍"
"Copy Files" = "󱁥"
Preferences = ""

[title_in_class.Alacritty]
"(.*) - NVIM" = "󱩼"

[title_in_class.firefox]
"Lemmy - .*Firefox" = ""
".*nitter — Mozilla Firefox" = ""
".* - Beehaw — Mozilla Firefox" = ""
".* - Apps on Google Play — Mozilla Firefox" = ""
"Beehaw - .*Firefox" = ""
"GitHub — Mozilla Firefox" = ""
"Frozen Lemmy - .*Firefox" = ""
"Google Calendar — Mozilla Firefox" = "󰸗"
"Voice - (.*) Archive — Mozilla Firefox" = "󱉙"
".* - Frozen Lemmy — Mozilla Firefox" = ""
".* / X — Mozilla Firefox" = ""
".*Android Apps on Google Play — Mozilla Firefox" = ""
"Voice - (.*) Spam — Mozilla Firefox" = "󰏲"
"Voice - (.*) Voicemail — Mozilla Firefox" = ""
".* - YouTube — Mozilla Firefox" = "󰗃"
".* - Google Drive — Mozilla Firefox" = ""
".* - Lemmy.ca — Mozilla Firefox" = ""
"Google Calendar - .* — Mozilla Firefox" = "󰸗"
"Voice - Calls — Mozilla Firefox" = "󰏲"
"X — Mozilla Firefox" = ""
".* - Google Search — Mozilla Firefox" = ""
".* - Lemmy — Mozilla Firefox" = ""
".*Mozilla Firefox Private Browsing" = "󰈉"
"Lemmy.ca - .*Firefox" = ""
"Voice - (.*) Messages — Mozilla Firefox" = "󰏲"

[title_in_class.pcmanfm]
Notebooks = "󰣞"
Pictures = "󰉏"
Templates = "󱧺"
".config" = "󱁿"
Public = "󰉌"
Torrents = "󰉍"
Videos = "󱧺"
"Copy Files" = "󱁥"
Music = "󱍙"
Preferences = ""
Downloads = "󰉍"
Documents = "󰲂"

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"[Ss]team" = "^(Friends List.*)?$"
"" = "^$"
"(?i)TestApp" = ""

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "<b>{name}:</b>{delim}{clients}"
workspace_empty = "<b>{name}</b>"
client = "<span alpha='70%'>{icon}</span>"
client_fullscreen = "｢{icon}｣"
client_active = "<span alpha='100%'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
