version = "1.1.14"

[class]
"/exe/" = "󰡶"
"/pdf/" = ""
"Alacritty" = ""
"Anydesk" = ""
"Ardour-5.9.0" = ""
"Bitwarden" = ""
"Cemu" = "︁"
"Chromium" = ""
"Chromium-browser" = ""
"Code" = ""
"CombatMaster.x86_64" = "󰜃"
"Element" = ""
"FTL.amd64" = ""
"FreeTube" = ""
"GParted" = "󰋊"
"Gimp" = ""
"Google-chrome" = ""
"Insomnia" = ""
"Microsoft Teams - Insiders" = "󰊻"
"Microsoft Teams - Preview" = "󰊻"
"Nightly" = ""
"Pinta" = "󰃣"
"Postman" = "󰇮"
"SchildiChat" = ""
"Slack" = "󰒱"
"Spotify" = ""
"Steam" = ""
"Telegram" = ""
"Thunderbird" = "󰇮"
"Wfica" = ""
"XEyes" = "󰈈"
"YARG" = "󰋄"
"Zim" = "󰏪"
"alacrittyclipboard" = ""
"anki" = ""
"at.yrlf.wl_mirror" = ""
"audacity" = ""
"blueberry.py" = "󰂯"
"chatall" = ""
"chromium" = ""
"citra" = "︁"
"clonehero" = "󰋄"
"code-oss" = ""
"com.github.weclaw2.ImageRoll" = ""
"com.github.wwmm.easyeffects" = ""
"com.obsproject.Studio" = "󰻂"
"copyq" = "󰅇"
"deluge" = "󱑤"
"discord" = ""
"dolphin-emu" = "︁"
"firefox" = ""
"firefoxdeveloperedition" = ""
"foot" = ""
"galculator" = "󰃬"
"gcr-prompter" = ""
"gnome-power-statistics" = ""
"gucharmap" = ""
"image-roll" = ""
"io.gpt4all.gpt4all-chat" = ""
"lmirtechconsole.exe" = ""
"org.gnome.Loupe" = ""
"mpv" = ""
"mpvrainsounds" = ""
"net.nokyan.Resources" = ""
"nheko" = ""
"obs" = "󰻂"
"org.inkscape.Inkscape" = ""
"org.kde.ark" = ""
"org.kde.dolphin" = "󰉋"
"org.kde.kcharselect" = ""
"org.kde.ksysguard" = ""
"org.qbittorrent.qBittorrent" = "󱑤"
"org.qutebrowser.qutebrowser" = ""
"org.remmina.Remmina" = ""
"org.telegram.desktop" = ""
"org.twosheds.iwgtk" = ""
"pavucontrol" = ""
"pcmanfm-gtk4" = "󰉋"
"pcmanfm-qt" = "󰉋"
"pinta" = "󰃣"
"polkit-gnome-authentication-agent0" = ""
"qtalarm" = "󰀠"
"r2modman" = ""
"rpcs4" = "︁"
"spotify" = ""
"steam" = ""
"steam_app_1266700" = "󰢚"
"steam_app_1623730" = "󰐝"
"steam_app_1817070" = "󱇪"
"steam_app_1817190" = "󱇪"
"steam_app_1872550" = "󰢚"
"steam_app_2281730" = "󰜃"
"steam_app_246620" = ""
"steam_app_714010" = "󰜃"
"steam_app_783770" = "󰜃"
"steam_app_803330" = "󰢚"
"steamwebhelper" = ""
"stoken-gui" = "󰌆"
"teams-for-linux" = "󰊻"
"telegramdesktop" = ""
"thunderbird" = "󰇮"
"vlc" = "󰕼"
"waydroid.com.citrix.Receiver" = ""
"wdisplays" = ""
"whatsapp-for-linux" = ""
"yakyak" = "󰋉"
"yuzu" = "︁"
"zim" = "󰏪"
DEFAULT = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
10 = "ten"
2 = "2"
4 = "four"
1 = "1"
0 = "0"
3 = "three"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
scratchpad = "11"
work = "12"

[title_in_class.Alacritty]
"(.*) - NVIM" = "󱩼"

[title_in_class.chromium]
"(?i)Github" = ""
"(?i)Dashboards -.*Chromium" = ""
"/Google/" = ""
"(?i)MAX.*Chromium" = ""
"(.*)INC. - Dashboard > Home - Chromium" = ""
"(.*) - YouTube.*Chromium" = ""

[title_in_class.firefox]
"(?i)Google Calendar.*Firefox" = ""
"(?i)Github" = ""
" - YouTube — Mozilla Firefox" = ""
"/Google/" = ""
".*Twitter — Mozilla Firefox" = ""
"(?i)Google Drive.*Firefox" = ""
"(?i)Google Play.*Firefox" = ""
"Firefox .*Private Browsing" = "󰈉"
"(?i)reddit.*Firefox" = ""
"(?i)drive.*Firefox" = ""
".*nitter — Mozilla Firefox" = ""

[title_in_class.pcmanfm-qt]
"Preferences" = ""

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)TestApp" = ""
"[Ss]team" = "^(Friends List.*)?$"
"(?i)fcitx" = ".*"
"" = "^$"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "<span color='#ff4040'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
