version = "1.1.14"

[class]
"/exe/" = ""
"/pdf/" = "󰈦"
"Alacritty" = ""
"Anydesk" = "󰢹"
"Bitwarden" = ""
"Cemu" = "󰜭"
"Chromium" = ""
"Chromium-browser" = ""
"Code" = ""
"CombatMaster.x86_64" = "󰜃"
"Element" = ""
"FTL.amd64" = ""
"FreeTube" = ""
"GParted" = "󰋊"
"Gimp" = ""
"Google-chrome" = ""
"Insomnia" = ""
"Microsoft Teams - Insiders" = "󰊻"
"Microsoft Teams - Preview" = "󰊻"
"Nightly" = ""
"Pinta" = "󰃣"
"Postman" = "󰇮"
"SchildiChat" = ""
"Slack" = "󰒱"
"Spotify" = ""
"Steam" = ""
"Telegram" = ""
"Thunderbird" = "󰇮"
"Wfica" = ""
"XEyes" = "󱗣"
"YARG" = "󰋄"
"Zim" = "󰏪"
"alacrittyclipboard" = ""
"anki" = ""
"at.yrlf.wl_mirror" = ""
"audacity" = ""
"blueberry.py" = "󰂯"
"chatall" = ""
"chromium" = ""
"citra" = ""
"clonehero" = "󰋄"
"code-oss" = ""
"com.github.weclaw2.ImageRoll" = ""
"com.github.wwmm.easyeffects" = "󰝚"
"com.obsproject.Studio" = ""
"copyq" = ""
"deluge" = ""
"discord" = ""
"dolphin-emu" = "󱢴"
"firefox" = ""
"firefoxdeveloperedition" = ""
"foot" = ""
"galculator" = "󰪚"
"gcr-prompter" = ""
"gnome-power-statistics" = "󰂑"
"gucharmap" = ""
"image-roll" = ""
"io.gpt4all.gpt4all-chat" = ""
"lmirtechconsole.exe" = ""
"mpv" = ""
"mpvrainsounds" = ""
"net.nokyan.Resources" = "󰉹"
"nheko" = ""
"obs" = ""
"org.gnome.Loupe" = ""
"org.inkscape.Inkscape" = ""
"org.kde.ark" = ""
"org.kde.dolphin" = "󰉋"
"org.kde.kcharselect" = ""
"org.qbittorrent.qBittorrent" = "󱑤"
"org.qutebrowser.qutebrowser" = "󰖟"
"org.remmina.Remmina" = ""
"org.telegram.desktop" = ""
"org.twosheds.iwgtk" = "󰖩"
"pavucontrol" = "󰕾"
"pcmanfm-gtk4" = "󰉋"
"pcmanfm-qt" = "󰉋"
"pinta" = "󰃣"
"polkit-gnome-authentication-agent-1" = ""
"polkit-gnome-authentication-agent0" = ""
"qtalarm" = "󰀠"
"r2modman" = "󰖷"
"rpcs4" = ""
"ryujinx" = "󰟡"
"spotify" = ""
"steam" = ""
"steam_app_1266700" = "󰢚"
"steam_app_1623730" = "󰐝"
"steam_app_1817070" = ""
"steam_app_1817190" = ""
"steam_app_1872550" = "󰢚"
"steam_app_2281730" = "󰜃"
"steam_app_246620" = ""
"steam_app_714010" = "󰜃"
"steam_app_783770" = "󰜃"
"steam_app_803330" = "󰢚"
"steamwebhelper" = ""
"stoken-gui" = "󰌆"
"teams-for-linux" = "󰊻"
"telegramdesktop" = ""
"thunderbird" = "󰇮"
"vlc" = "󰕼"
"waydroid.com.citrix.Receiver" = ""
"wdisplays" = ""
"whatsapp-for-linux" = ""
"yakyak" = "󰋉"
"yuzu" = "󰟡"
"zim" = "󰏪"
DEFAULT = ""

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
0 = "0"
1 = "1"
2 = "2"
3 = "3"
4 = "4"
5 = "5"
6 = "6"
7 = "7"
8 = "8"
9 = "9"
10 = "10"

[title_in_class.Alacritty]
"(.*) - NVIM" = "󱩼"

[title_in_class.chromium]
".* - Apps on Google Play  - Chromium" = ""
".* - Beehaw  - Chromium" = ""
".* - Frozen Lemmy  - Chromium" = ""
".* - Google Drive  - Chromium" = ""
".* - Google Search  - Chromium" = ""
".* - Lemmy  - Chromium" = ""
".* - Lemmy.ca  - Chromium" = ""
".* - YouTube  - Chromium" = ""
".* / X  - Chromium" = ""
".*Android Apps on Google Play  - Chromium" = ""
".*nitter  - Chromium" = ""
"Beehaw - .*Chromium" = ""
"Dashboards - Chromium" = ""
"Frozen Lemmy - .*Chromium" = ""
"GitHub  - Chromium" = ""
"Google Calendar  - Chromium" = "󰸗"
"Google Calendar - .*  - Chromium" = "󰸗"
"INC. - Dashboard > Home - Chromium" = "󰥔"
"Lemmy - .*Chromium" = ""
"Lemmy.ca - .*Chromium" = ""
"MAX.*Chromium" = ""
"Voice - (.*) Archive  - Chromium" = "󱉙"
"Voice - (.*) Messages  - Chromium" = "󰏲"
"Voice - (.*) Spam  - Chromium" = "󰏲"
"Voice - (.*) Voicemail  - Chromium" = ""
"Voice - Calls  - Chromium" = "󰏲"
"X  - Chromium" = ""

[title_in_class.firefox]
".* - Apps on Google Play — Mozilla Firefox" = ""
".* - Beehaw — Mozilla Firefox" = ""
".* - Frozen Lemmy — Mozilla Firefox" = ""
".* - Google Drive — Mozilla Firefox" = ""
".* - Google Search — Mozilla Firefox" = ""
".* - Lemmy — Mozilla Firefox" = ""
".* - Lemmy.ca — Mozilla Firefox" = ""
".* - YouTube — Mozilla Firefox" = ""
".* / X — Mozilla Firefox" = ""
".*Android Apps on Google Play — Mozilla Firefox" = ""
".*Mozilla Firefox Private Browsing" = "󰈉"
".*nitter — Mozilla Firefox" = ""
"Beehaw - .*Firefox" = ""
"Frozen Lemmy - .*Firefox" = ""
"GitHub — Mozilla Firefox" = ""
"Google Calendar - .* — Mozilla Firefox" = "󰸗"
"Google Calendar — Mozilla Firefox" = "󰸗"
"Lemmy - .*Firefox" = ""
"Lemmy.ca - .*Firefox" = ""
"Voice - (.*) Archive — Mozilla Firefox" = "󱉙"
"Voice - (.*) Messages — Mozilla Firefox" = "󰏲"
"Voice - (.*) Spam — Mozilla Firefox" = "󰏲"
"Voice - (.*) Voicemail — Mozilla Firefox" = ""
"Voice - Calls — Mozilla Firefox" = "󰏲"
"X — Mozilla Firefox" = ""

[title_in_class.pcmanfm-qt]
".config" = "󱁿"
"Documents" = "󰲂"
"Downloads" = "󰉍"
"Music" = "󱍙"
"Notebooks" = "󰣞"
"Pictures" = "󰉏"
"Preferences" = ""
"Public" = "󰉌"
"Templates" = "󱧺"
"Torrents" = "󰉍"
"Videos" = "󱧺"

[title_in_class_active]

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)TestApp" = ""
"[Ss]team" = "^(Friends List.*)?$"
"(?i)fcitx" = ".*"
"" = "^$"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "<b>{name}:</b>{delim}{clients}"
workspace_empty = "<b>{name}</b>"
client = "<span alpha='70%'>{icon}</span>"
client_fullscreen = "｢{icon}｣"
client_active = "<span alpha='100%'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
