# Default apps
#env = PASSWORDMANAGER,bitwarden > /dev/null
#env = PASSWORDMANAGERBACKGROUND,pidof bitwarden > /dev/null || while true ; do (bitwarden > /dev/null); done
#env = FILEMANAGER,dolphin > /dev/null
#env = CLIPBOARDMANAGERBACKGROUND,pidof copyq > /dev/null || copyq --start-server > /dev/null
#env = CLIPBOARDMANAGERSHOW,copyq show > /dev/null
#env = BROWSER,librewolf > /dev/null

# Startup apps
exec-once = while ! pidof waybar > /dev/null; do sleep 0.2; done; equibop --Start-minimized > /dev/null
exec-once = pidof librewolf > /dev/null || librewolf > /dev/null
exec-once = while ! pidof waybar > /dev/null; do sleep 0.2; done; pidof qbittorrent > /dev/null || qbittorrent --no-splash > /dev/null
exec-once = while ! pidof waybar > /dev/null; do sleep 0.2; done; pidof steam > /dev/null || steam-run steam -nochatui -nofriendsui -silent > /dev/null
exec-once = while ! pidof waybar > /dev/null; do sleep 0.2; done; pidof neochat > /dev/null || neochat > /dev/null
#exec-once = while ! pidof waybar > /dev/null; do sleep 0.2; done; element-desktop --hidden > /dev/null
exec-once = while ! pidof waybar > /dev/null; do sleep 0.2; done; pidof Telegram > /dev/null || Telegram -startintray > /dev/null
bind = SUPER, w, exec, ~/.config/scripts/lights.sh

# Sounds
bind = SUPER, o, closewindow, class:mpvsounds
bind = ALT, q, closewindow, class:mpvsounds
bind = SUPER, o, closewindow, class:spotify
#bind = SUPER, minus, exec, hyprctl dispatch closewindow mpvrainsounds & pkill spotify & env PIPEWIRE_NODE=alsa_output.pci-0000_06_00.hdmi-stereo mpv --wayland-app-id=mpvrainsounds --start=0 --loop --pause=no --background=color --background-color=0/0/0/.03 --player-operation-mode=pseudo-gui ~/Documents/fire.ogg
bind = SUPER, APOSTROPHE, exec, hyprctl dispatch closewindow class:mpvsounds > /dev/null & hyprctl dispatch closewindow class:spotify > /dev/null & mpv --wayland-app-id=mpvsounds --start=0 --loop --pause=no --background=color --background-color=0/0/0/.03 --player-operation-mode=pseudo-gui ~/Documents/fire.opus > /dev/null
exec-once = swayidle timeout 660 "hyprctl dispatch closewindow class:at\.yrlf\.wl_mirror & hyprctl dispatch closewindow class:mpvsounds & hyprctl dispatch closewindow class:spotify"
windowrule = workspace 9 silent,class:(mpvsounds)

# Display settings
monitorv2 {
	output = eDP-1
	mode = highrr
	position = auto
	scale = 1.25
}
exec = xrandr --output eDP-1 --primary
env = GDK_SCALE,1.25
env = STEAM_FORCE_DESKTOPUI_SCALING,1.25

# Input settings
device {
	name = logitech-usb-receiver
	sensitivity = -0.85
	accel_profile = flat
	repeat_delay = 225
	repeat_rate = 8
}
device {
	name = logitech-g502-hero-gaming-mouse
	sensitivity = -0.6
	accel_profile = flat
	repeat_delay = 225
	repeat_rate = 8
}
device {
	name = wacom-multitouch-sensor-finger
	enabled=0
}
device {
	name = charachorder-charachorder-two-s3-mouse
	sensitivity = -0.8
	accel_profile = flat
	scroll_factor = 0.1
}
device {
	name = sony-interactive-entertainment-dualsense-wireless-controller-touchpad
	enabled=0
}
device {
	name = sony-interactive-entertainment-wireless-controller-touchpad
	enabled=0
}
