#exec-once = dconf write /org/gnome/desktop/interface/cursor-size 32
#exec-once = dconf write /org/gnome/desktop/interface/cursor-theme "'Posy_Cursor_Black'"
#exec-once = dconf write /org/gnome/desktop/interface/document-font-name "'Noto Sans Medium 11'"
#exec-once = dconf write /org/gnome/desktop/interface/enable-animations true
#exec-once = dconf write /org/gnome/desktop/interface/font-name "'Noto Sans Medium 11'"
#exec-once = dconf write /org/gnome/desktop/interface/gtk-theme "'ancomblackred'"
#exec-once = dconf write /org/gnome/desktop/interface/icon-theme "'Flat-Remix-Red-Dark'"
#exec-once = dconf write /org/gnome/desktop/interface/monospace-font-name "'Noto Sans Mono Medium 11'"
#exec-once = dconf write /org/gnome/desktop/interface/accent-color "'#cc0000'"
#exec-once = dconf write /org/gnome/desktop/wm/preferences/button-layout "''"
#exec-once = dconf write /org/gnome/desktop/interface/color-scheme "'prefer-dark'"
#exec-once = hyprctl setcursor Posy_Cursor_Black 32
#exec-once = while ! pidof swww-daemon > /dev/null; do sleep 0.2; done; swww img ~/.config/wallpaper/wallpaper.png
env = GTK_OVERLAY_SCROLLING,1
env = HYPRCURSOR_SIZE,32
env = HYPRCURSOR_THEME,Posy_Cursor_Black
env = QT_AUTO_SCREEN_SCALE_FACTOR,0
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY,1
env = XCURSOR_SIZE,32
env = XCURSOR_THEME,Posy_Cursor_Black
env = _JAVA_AWT_WM_NONREPARENTING,1
