dwindle {
	pseudotile = no
	preserve_split = yes
	single_window_aspect_ratio = 16 9
	precise_mouse_move = true
	single_window_aspect_ratio_tolerance = 0.1
}

ecosystem {
	no_donation_nag = true
}

general {
	snap {
		enabled = true
		window_gap = 25
		monitor_gap = 15
	}
}

misc {
	disable_autoreload = true
	key_press_enables_dpms = true
	enable_anr_dialog = true
	anr_missed_pings = 5
	allow_session_lock_restore = 1
}

monitorv2 {
	output = 
	mode = highrr
	position = auto
}
