# Brightness
bindel	=,XF86MonBrightnessUp, exec, $lightup
bindel	=,XF86MonBrightnessDown, exec, $lightdown

# Media
bindl	=,XF86AudioPlay, exec, playerctl play
bindl	=,XF86AudioPause, exec, playerctl pause
bindl	=,XF86AudioNext, exec, playerctl next
bindl	=,XF86AudioPrev, exec, playerctl previous

# Menus
bind	=,XF86PowerOff, exec, $power

# Move/resize windows
bindm	= SUPER, mouse:272, movewindow
bindm	= SUPER, mouse:273, resizewindow

# Volume
bindel	=,XF86AudioRaiseVolume, exec, $volup
bindel	=,XF86AudioLowerVolume, exec, $voldown
bindl	=,XF86AudioMute, exec, $volmute
bindl	=,XF86AudioMicMute, exec, $micmute
